name: CICD Pipeline

on:
  workflow_call:

jobs:
  code:
    uses: ./.github/workflows/code.yml # workflow called
  build:
    needs: code
    uses: ./.github/workflows/build.yml
  test:
    needs: build
    uses: ./.github/workflows/test.yml
  deploy:
    needs: test
    uses: ./.github/workflows/deploy.yml
