# Name of the Workflow.
name: Code

# When the workflow should run.
on:
  workflow_call:

# Jobs in workflow. 
jobs:
  code-checkout:
    runs-on: ubuntu-latest

    # Steps in workflow.
    steps:
      - name: Clone the code
        uses: actions/checkout@v5
      - name: Print the message
        run: echo "Code Cloned"
    
