

  # Name of the Workflow.
name: Deploy

# When the workflow should run.
on:
  workflow_call:
  # push: whenever code is pushed to GitHub, the workflow automatically runs. 
  # workflow_call: when this workflow needs to be called from another workflow.
  # workflow_dispatch: whenever you want the workflow to be called manually 
  # schedule: whenever you want the workflow to run at a specific time.
  
# Jobs in workflow. 
jobs:
  code-checkout:
    runs-on: ubuntu-latest

    # Steps in workflow.
    steps:
      - name: Deploy the code
        run: echo "Code Deployed to AWS EC@ instance"
